### ISSUE TITLE
Add a way to configure a different annotated JDK

### ISSUE THREAD

**Issue by netdpb** [eisop/checker-framework#671]
Right now the annotated JDK is included in the artifact, so the only way to use an alternative is to build locally. It would be good, especially for JSpecify, to make it possible to substitute an alternative annotated JDK.

**Comment by wmdietl** [comment]
This turned out to be already implemented: https://github.com/eisop/checker-framework/blob/feecad2aa6fece99c2597f23a7692fa5f198e4c8/framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java#L888 looks up the `annotated-jdk` resources relative to the type factory.

https://github.com/jspecify/jspecify-reference-checker/pull/188 uses this in the JSpecify reference checker.
